//
//  RChartIdPrefixes.h
//  Riker
//
//  Created by PEVANS on 10/11/17.
//  Copyright © 2017 Riker. All rights reserved.
//

#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_WEIGHT_LIFTED_TIME;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_WEIGHT_LIFTED_AVG_TIME;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_WEIGHT_LIFTED_DIST;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_WEIGHT_LIFTED_DIST_TIME;

FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_REPS_TIME;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_REPS_AVG_TIME;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_REPS_DIST;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_REPS_DIST_TIME;

FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_TBS_TIME;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_TBS_AVG_TIME;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_TBS_DIST;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_TBS_DIST_TIME;

FOUNDATION_EXPORT NSInteger const MAX_STRENGTH_CHARTS_PER_PREFIX;
FOUNDATION_EXPORT NSInteger const MAX_BODY_CHARTS_PER_PREFIX;

FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_BODY_WEIGHT;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_ARM_SIZE;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_NECK_SIZE;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_CHEST_SIZE;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_FOREARM_SIZE;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_WAIST_SIZE;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_CALF_SIZE;
FOUNDATION_EXPORT NSString * const CHART_ID_PREFIX_THIGH_SIZE;
